FROM ghcr.io/oran-testing/components_base

RUN git clone https://github.com/oran-testing/uu-agent /uuagent

RUN mkdir -p /uuagent/build

WORKDIR /uuagent/build

RUN cmake ../ && \
    make -j$(nproc) && \
    make install

CMD [ "sh", "-c", "/usr/local/bin/uuagent --config /uu-agent.conf" ]
