FROM ghcr.io/oran-testing/components_base

RUN git clone https://github.com/oran-testing/jammer /jammer

RUN mkdir -p /jammer/build

WORKDIR /jammer/build

RUN cmake ../ && \
    make -j$(nproc) && \
    make install

WORKDIR /jammer

CMD [ "sh", "-c", "/usr/local/bin/jammer --config /jammer.yaml $ARGS" ]

