force_build: true
build_spec:
  - component: "sni5gect"
    docker_image: "ghcr.io/oran-testing/sni5gect"
    pull: false

run_spec:
  - component: "sni5gect"
    name: "sni5gect_uhd_1"
    config_file: "configs/sni5gect/srsgnb_band3.yaml"
    rf:
      type: "b200"
