external_targets:
  - name: "sni5gect_runner"
    token: "testing_token"
    host: "192.168.0.10"
    port: 1343

run_spec:
#  - component: "rtue"
#    name: "rtue_uhd_1"
#    config_file: "configs/srsran/ue_uhd.conf"
#    rf:
#      type: "b200"
#  - component: "uu_agent"
#    name: "uuagent_uhd_1"
#    config_file: "configs/uuagent/gnb_test.conf"
#    rf:
#      type: "b200"

  - component: "sni5gect"
    name: "sni5gect_uhd_1"
    config_file: "configs/sni5gect/srsgnb_band3.yaml"
    rf:
      type: "b200"
#    target: "sni5gect_runner"
