processes:
  - type: "oai_ue"
    id: "oai_ue_usrp_1"
    args:
      - "-r"
      - "106"
      - "--numerology"
      - "1"
      - "--band"
      - "78"
      - "-C"
      - "3619200000"
      - "--ssb"
      - "516"
      - "--ue-fo-compensation"
      - "-E"
      - "--uicc0.imsi"
      - "001010000000001"
      - "--uicc0.key"
      - "fec86ba6eb707ed08905757b1bb44b8f"
      - "--uicc0.opc"
      - "C42449363BBAD02B66D16BC975D77CC1"
      - "--uicc0.dnn"
      - "internet"
      - "--uicc0.nssai_sst"
      - "1"
    rf:
      type: "b200"
      images_dir: "/usr/share/uhd/images/"
