name: Run all unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r controller/requirements.txt

      - name: Run controller unit tests
        run: |
          cd controller/src
          pytest -v

  system_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        system_test_config:
          # Environment tests: check that controller passes required env
          - ci_configs/system_environment_tests/test_control_api.yaml
          - ci_configs/system_environment_tests/test_uhd_images.yaml
          - ci_configs/system_environment_tests/test_influx_access.yaml
          - ci_configs/system_environment_tests/test_conf_pass.yaml

          # Build tests: check that all components still build
          - ci_configs/component_build_tests/test_build_ssb_spoofer.yaml
          - ci_configs/component_build_tests/test_build_jammer.yaml
          - ci_configs/component_build_tests/test_build_uuagent.yaml
          - ci_configs/component_build_tests/test_build_sni5gect.yaml
          - ci_configs/component_build_tests/test_build_rtue.yaml

          # Pull tests: check that all components are pullable
          - ci_configs/component_pull_tests/test_pull_ssb_spoofer.yaml
          - ci_configs/component_pull_tests/test_pull_jammer.yaml
          - ci_configs/component_pull_tests/test_pull_uuagent.yaml
          - ci_configs/component_pull_tests/test_pull_sni5gect.yaml
          - ci_configs/component_pull_tests/test_pull_rtue.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install uhd-host -y
          ./scripts/system_setup.sh --no-confirm
          docker compose build

      - name: Run system tests
        run: |
          sed -i "s|DOCKER_CONTROLLER_INIT_CONFIG=.*|DOCKER_CONTROLLER_INIT_CONFIG=${{ matrix.system_test_config }}|g" .env
          docker compose up --abort-on-container-exit --exit-code-from controller


